### PR TITLE
Mask kafka ccloud secrets in the logs.

### PR DESCRIPTION
**Pull request by pbadani**
Kafka api key and secret values are inadvertently being logged on ccloud. This PR updates the regex for passwords such that the masked configs don't log them.
This fork didnt look like under active development.

### CODE REVIEW

**Comment by C0urante** [comment]
😱  that's not good.
I think we should target `v1.3.1.x` with this; IIRC that's the version we're building off of right now for cloud (see https://github.com/confluentinc/cc-docker-connect/blob/beda32415d08578b23a08a1b64a27c7c317a9ef4/cc-connect/Dockerfile#L124).

**Review by C0urante — APPROVED** [review]
LGTM, thanks @pbadani!

**Comment by pbadani** [comment]
> LGTM, thanks @pbadani!

@C0urante Would you be looking to releasing this. The process for this repo looks a bit different.

**Comment by C0urante** [comment]
@pbadani I don't have bandwidth to do this release right now. We do have a [Wiki doc](https://confluentinc.atlassian.net/wiki/spaces/CONNECT/pages/1657112437/Team2+Connector+Packaging+Release) with instructions on how to release it to cloud, though.

**Pull request merged**
