### PR TITLE
RCCA-16793: Correctly populate the lsnSeen cache during searching phase

### PR DESCRIPTION
**Pull request by rajdangwal**
Refer to this slack thread for the issue and the fix: https://confluent.slack.com/archives/C06CKF566CS/p1707371950919059

Testing:
Manually tested the scenario where the connector was failing earlier. The connector is not failing now.
Also, for other paths the connector is functioning correctly.

### CODE REVIEW

**Review by sudeshwasnik — CHANGES_REQUESTED** [review]
Hi @rajdangwal  nice find ! 

Do we need to make such a drastic change that affects all unrelated Decoders/Streams classes etc ? 
Couple of other approaches could be -> 
1. What if we run the `processor` for initial_chunk ([here](https://github.com/debezium/debezium/blob/a8cda23ef2baf982d5e9c865500cdc24516866c7/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java#L173-L176)) ? We need to make sure that `resumeFromLsn()` in WalPositionLocator returns Optional.empty() for this case. 
2. Everything that has been skipped must be marked as `lsnSeen` ([here](https://github.com/debezium/debezium/blob/20af6ab0770b7d4881abdb5bdc04402d5e2f9581/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java#L148-L150))

IIUC we should use `WalPositionLocator` to track and store first/last LSN. Decoders should not worry about tracking starting "LSN"s, and so lets always invoke `processor` in decoder, which then would add into lsnSeen whenever required.

**Comment by sudeshwasnik** [comment]
Also, the current PR may create many "sync" issues in future. If we want to go with interface level changes, we can consider fixing it in upstream directly.

**Comment by rajdangwal** [comment]
Thanks for the review @sudeshwasnik 
> 1. What if we run the `processor` for initial_chunk ([here](https://github.com/debezium/debezium/blob/a8cda23ef2baf982d5e9c865500cdc24516866c7/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java#L173-L176)) ? We need to make sure that `resumeFromLsn()` in WalPositionLocator returns Optional.empty() for this case.

The issue with calling processor in suggested path is that we don't know if the chunk is lastMessage or not (which is the fourth parameter to be passed to the [processMessage](https://github.com/debezium/debezium/blob/a8cda23ef2baf982d5e9c865500cdc24516866c7/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/wal2json/StreamingWal2JsonMessageDecoder.java#L249) method). We would only know that after getting the next chunk. That's the reason for buffering the previous chunk.

> 2. Everything that has been skipped must be marked as `lsnSeen` ([here](https://github.com/debezium/debezium/blob/20af6ab0770b7d4881abdb5bdc04402d5e2f9581/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java#L148-L150))

Good suggestion. Looks like the `lsnSeen` cache can be populated in the block you suggested, as the `passMessages` flag will always be true in the searching phase. The only issue that I can see here is that in the later block where we are [reseting the lsnSeen cache](https://github.com/debezium/debezium/blob/20af6ab0770b7d4881abdb5bdc04402d5e2f9581/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java#L153-L154), we would be adding every LSN that is encountered during the streaming phase to the cache. Maybe introducing an additional flag would suffice. I will check it.

> IIUC we should use `WalPositionLocator` to track and store first/last LSN. Decoders should not worry about tracking starting "LSN"s, and so lets always invoke `processor` in decoder, which then would add into lsnSeen whenever required.

The `lsnSeen` cache tracks all the LSNs seen during the searching phase and not just the first/last LSN. Not sure why you said otherwise!

> Also, the current PR may create many "sync" issues in future. If we want to go with interface level changes, we can consider fixing it in upstream directly.

Debezium has stopped releasing changes on 1.9 branch. So we won't be doing further syncs from upstream.
Also, the fix is specific to wal2json plugin which is not supported by Debezium anymore, so can't be contributed back to Debezium.

**Review by sudeshwasnik — APPROVED** [review]
Looks good ! thanks @rajdangwal  !

**Pull request merged**
