### PR TITLE
Patch database.server.name validator to allow dot

### PR DESCRIPTION
**Pull request by Cyril-Engels**
Patch database.server.name validator to allow dot as it's causing connectors previously running to fail

### CODE REVIEW

**Comment by C0urante** [comment]
This is going to cause incidents if we revert and people start creating invalid connectors. Why aren't we patching the logic here instead of reverting it? This information should be included in the PR description.

**Review by ddasarathan — APPROVED** [review]

**Review by C0urante — CHANGES_REQUESTED** [review]
This is going to cause incidents if we revert and people start creating invalid connectors. Why aren't we patching the logic here instead of reverting it? This information should be included in the PR description.

**Comment by Cyril-Engels** [comment]
> This is going to cause incidents if we revert and people start creating invalid connectors. Why aren't we patching the logic here instead of reverting it? This information should be included in the PR description.

@C0urante The problem is the connectors regarded as invalid were actually running. But now they failed validation. Tho this in an improvement, this is backward incompatible.

**Comment by C0urante** [comment]
I understand that, but that doesn't really explain why we're not patching this logic instead of reverting it.

**Comment by Cyril-Engels** [comment]
> I understand that, but that doesn't really explain why we're not patching this logic instead of reverting it.
@C0urante If we have instances of various special characters, I don't think it make sense to include all of them. Looks like currently wethe only different case is dot. I think we are good to add it then.

**Comment by Cyril-Engels** [comment]
@C0urante Updated, PTAL again

**Review by C0urante — APPROVED** [review]
LGTM, but we should update the description and the PR title.

**Pull request merged**
